<?xml version="1.0" encoding="utf-8"?><Database Name="EventsToCalendar" Class="CalendarDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=EventsToCalendar;Integrated Security=True" SettingsObjectName="WpfApplication1.Properties.Settings" SettingsPropertyName="EventsToCalendarConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EventsCalendar" Member="EventsCalendars">
    <Type Name="EventsCalendar">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventCal" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>